# Generated by Django 3.2.4 on 2021-08-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_loghistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogByDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ['date', 'category'],
            },
        ),
    ]
